### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by jessepeterson** [smallstep/pkcs7#10]
Hello! Looks like the patch branch got merged to master! Thats great and thanks for the work!

I'd like to kindly suggest either a rename or a switch of the default branch name to be main. Thanks!

**Comment by hslatman** [comment]
Hey @jessepeterson, nice catch! Just renamed the branch.

For reference, to update local clones:

```console
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

Also a nice reminder to rename the module, and start tagging releases 😅
