### ISSUE TITLE
SHA-256 not supported for RSA encryption

### ISSUE THREAD

**Issue by clarkmcc** [smallstep/pkcs7#11]
I'm trying to verify the [Azure attestation signature](https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tabs=linux#response-2) using this library and am able to successfully parse the signature, but validation fails with the following error.
```
pkcs7: unsupported digest "1.2.840.113549.1.1.11" for encryption algorithm "1.2.840.113549.1.1.1"
```

**Comment by hslatman** [comment]
Hey @clarkmcc, looks like this case wasn't handled yet. I've opened a PR: https://github.com/smallstep/pkcs7/pull/12. Need to verify the allowed algorithms. The example from Microsoft succeeds validation with this single algorithm patched.

**Comment by clarkmcc** [comment]
Fantastic news! Thanks for the quick turnaround.

**Comment by hslatman** [comment]
@clarkmcc the PR was merged. Note that we've also changed the module name in https://github.com/smallstep/pkcs7/pull/16, so you should now be able to import it as `github.com/smallstep/pkcs7`.

**Comment by clarkmcc** [comment]
I meant to ask about that. I had to jump through some hoops to work around that, so this is a great improvement! Thanks for your work on this.
