### ISSUE TITLE
Rename module and tag release

### ISSUE THREAD

**Issue by hslatman** [smallstep/pkcs7#14]
- [x] Rename module: #16 
- [x] Tag release https://github.com/smallstep/pkcs7/releases/tag/v0.1.0

**Comment by LordNoteworthy** [comment]
Hello @hslatman 

After you forked the project, there has been a couple of commits. Maybe we should already make a release out of that and call it v1.0.0 ?

**Comment by RichardLaos** [comment]
Is a release still in the works for this library?

**Comment by AkihiroSuda** [comment]
If the project is still not ready for v1.0.0, could you just tag it as "v1.0.0-beta.0" or "v0.9.0" ?

**Comment by hslatman** [comment]
I've tagged `v0.1.0`: https://github.com/smallstep/pkcs7/releases/tag/v0.1.0. This allows us iterating a bit more, getting things in a better shape before a `v1.0.0.`.
